
import React, { createContext, useState, useContext, ReactNode } from 'react';

// 1. Define Supported Languages
export type LanguageCode = 'id' | 'en' | 'zh' | 'es' | 'hi' | 'ar' | 'fr' | 'de' | 'ja' | 'ko';

export const LANGUAGES: { code: LanguageCode; name: string }[] = [
  { code: 'id', name: 'Indonesia' },
  { code: 'en', name: 'English' },
  { code: 'zh', name: '中文 (Chinese)' },
  { code: 'es', name: 'Español' },
  { code: 'hi', name: 'हिन्दी (Hindi)' },
  { code: 'ar', name: 'العربية (Arabic)' },
  { code: 'fr', name: 'Français' },
  { code: 'de', name: 'Deutsch' },
  { code: 'ja', name: '日本語 (Japanese)' },
  { code: 'ko', name: '한국어 (Korean)' },
];

// 2. Dictionary / Translations
const DICTIONARY: Record<LanguageCode, Record<string, string>> = {
  id: {
    agenda: 'AGENDA',
    price: 'Harga',
    benefit: 'Benefit',
    profit: 'Keuntungan',
    select: 'PILIH',
    approved: 'APPROVED',
    recommended: 'RECOMMENDED',
    contact_us: 'HUBUNGI KAMI',
    confirm_order: 'KONFIRMASI PESANAN',
    back: 'KEMBALI',
    cancel: 'BATAL',
    order_confirmation: 'KONFIRMASI PESANAN',
    please_review: 'Mohon periksa pilihan Anda di bawah ini',
    selected: 'TERPILIH',
    total_profit: 'TOTAL KEUNTUNGAN',
    claim_now: 'KLAIM SEKARANG',
    modal_price: 'HARGA MODAL',
    total_withdraw: 'TOTAL PENARIKAN',
    limited_offer: 'Penawaran Terbatas • Eksklusif Akhir Pekan',
    design_special: 'DESAIN SPESIAL PREMIUM',
    weekend_collection: 'KOLEKSI AKHIR PEKAN',
    payment_title: 'Detail Pembayaran',
    payment_note: 'Catatan: Apabila pembayaran telah dilakukan, silakan konfirmasikan bukti pembayarannya kepada Customer Service',
    confirm_wa: 'KONFIRMASI WHATSAPP',
    bank: 'Bank',
    account_name: 'Nama Rekening',
    account_no: 'No. Rekening',
    nominal: 'Nominal',
    // Login Page
    full_name: 'Nama Lengkap',
    phone_number: 'Nomor Telepon',
    password: 'Kata Sandi',
    login: 'Masuk',
    processing: 'Memproses...',
    enter_world: 'MASUKKAN DUNIA GUCCI',
    copyright: '© 2025 Guccio Gucci S.p.A.',
    fill_fields: 'Harap isi semua kolom',
  },
  en: {
    agenda: 'AGENDA',
    price: 'Price',
    benefit: 'Benefit',
    profit: 'Profit',
    select: 'SELECT',
    approved: 'APPROVED',
    recommended: 'RECOMMENDED',
    contact_us: 'CONTACT US',
    confirm_order: 'CONFIRM ORDER',
    back: 'BACK',
    cancel: 'CANCEL',
    order_confirmation: 'ORDER CONFIRMATION',
    please_review: 'Please review your selection below',
    selected: 'SELECTED',
    total_profit: 'TOTAL PROFIT',
    claim_now: 'CLAIM NOW',
    modal_price: 'CAPITAL PRICE',
    total_withdraw: 'TOTAL WITHDRAW',
    limited_offer: 'Limited Availability • Weekend Exclusive',
    design_special: 'PREMIUM SPECIAL DESIGN',
    weekend_collection: 'WEEKEND COLLECTION',
    payment_title: 'Payment Details',
    payment_note: 'Note: Once payment is made, please confirm the proof of payment to Customer Service',
    confirm_wa: 'CONFIRM WHATSAPP',
    bank: 'Bank',
    account_name: 'Account Name',
    account_no: 'Account No',
    nominal: 'Amount',
    // Login Page
    full_name: 'Full Name',
    phone_number: 'Phone Number',
    password: 'Password',
    login: 'Login',
    processing: 'Processing...',
    enter_world: 'ENTER THE WORLD OF GUCCI',
    copyright: '© 2025 Guccio Gucci S.p.A.',
    fill_fields: 'Please fill in all fields',
  },
  zh: {
    agenda: '议程',
    price: '价格',
    benefit: '利益',
    profit: '利润',
    select: '选择',
    approved: '已批准',
    recommended: '推荐',
    contact_us: '联系我们',
    confirm_order: '确认订单',
    back: '返回',
    cancel: '取消',
    order_confirmation: '订单确认',
    please_review: '请在下方查看您的选择',
    selected: '已选',
    total_profit: '总利润',
    claim_now: '立即索赔',
    modal_price: '资本价格',
    total_withdraw: '提款总额',
    limited_offer: '数量有限 • 周末独家',
    design_special: '高级特别设计',
    weekend_collection: '周末系列',
    payment_title: '付款详情',
    payment_note: '注意：付款后，请向客户服务确认付款凭证',
    confirm_wa: 'WhatsApp 确认',
    bank: '银行',
    account_name: '账户名称',
    account_no: '账号',
    nominal: '金额',
    // Login Page
    full_name: '全名',
    phone_number: '电话号码',
    password: '密码',
    login: '登录',
    processing: '处理中...',
    enter_world: '进入 GUCCI 世界',
    copyright: '© 2025 Guccio Gucci S.p.A.',
    fill_fields: '请填写所有字段',
  },
  es: {
    agenda: 'AGENDA',
    price: 'Precio',
    benefit: 'Beneficio',
    profit: 'Ganancia',
    select: 'SELECCIONAR',
    approved: 'APROBADO',
    recommended: 'RECOMENDADO',
    contact_us: 'CONTÁCTENOS',
    confirm_order: 'CONFIRMAR PEDIDO',
    back: 'ATRÁS',
    cancel: 'CANCELAR',
    order_confirmation: 'CONFIRMACIÓN DE PEDIDO',
    please_review: 'Por favor revise su selección a continuación',
    selected: 'SELECCIONADO',
    total_profit: 'GANANCIA TOTAL',
    claim_now: 'RECLAMAR AHORA',
    modal_price: 'PRECIO CAPITAL',
    total_withdraw: 'RETIRO TOTAL',
    limited_offer: 'Disponibilidad Limitada • Exclusivo de Fin de Semana',
    design_special: 'DISEÑO ESPECIAL PREMIUM',
    weekend_collection: 'COLECCIÓN DE FIN DE SEMANA',
    payment_title: 'Detalles de Pago',
    payment_note: 'Nota: Una vez realizado el pago, confirme el comprobante de pago al Servicio al Cliente',
    confirm_wa: 'CONFIRMAR WHATSAPP',
    bank: 'Banco',
    account_name: 'Nombre de Cuenta',
    account_no: 'No. de Cuenta',
    nominal: 'Monto',
    // Login Page
    full_name: 'Nombre Completo',
    phone_number: 'Número de Teléfono',
    password: 'Contraseña',
    login: 'Iniciar Sesión',
    processing: 'Procesando...',
    enter_world: 'ENTRAR AL MUNDO DE GUCCI',
    copyright: '© 2025 Guccio Gucci S.p.A.',
    fill_fields: 'Por favor complete todos los campos',
  },
  hi: {
    agenda: 'एजेंडा',
    price: 'कीमत',
    benefit: 'लाभ',
    profit: 'मुनाफा',
    select: 'चुनें',
    approved: 'स्वीकृत',
    recommended: 'अनुशंसित',
    contact_us: 'संपर्क करें',
    confirm_order: 'आर्डर की पुष्टि करें',
    back: 'वापस',
    cancel: 'रद्द करें',
    order_confirmation: 'आर्डर पुष्टिकरण',
    please_review: 'कृपया नीचे अपने चयन की समीक्षा करें',
    selected: 'चयनित',
    total_profit: 'कुल मुनाफा',
    claim_now: 'अभी दावा करें',
    modal_price: 'पूंजी मूल्य',
    total_withdraw: 'कुल निकासी',
    limited_offer: 'सीमित उपलब्धता • सप्ताहांत विशेष',
    design_special: 'प्रीमियम विशेष डिजाइन',
    weekend_collection: 'सप्ताहांत संग्रह',
    payment_title: 'भुगतान विवरण',
    payment_note: 'नोट: भुगतान हो जाने के बाद, कृपया ग्राहक सेवा को भुगतान प्रमाण की पुष्टि करें',
    confirm_wa: 'व्हाट्सएप पुष्टि',
    bank: 'बैंक',
    account_name: 'खाता नाम',
    account_no: 'खाता संख्या',
    nominal: 'राशि',
    // Login Page
    full_name: 'पूरा नाम',
    phone_number: 'फ़ोन नंबर',
    password: 'पासवर्ड',
    login: 'लॉग इन',
    processing: 'प्रक्रिया जारी है...',
    enter_world: 'GUCCI की दुनिया में प्रवेश करें',
    copyright: '© 2025 Guccio Gucci S.p.A.',
    fill_fields: 'कृपया सभी फ़ील्ड भरें',
  },
  ar: {
    agenda: 'جدول أعمال',
    price: 'السعر',
    benefit: 'الفائدة',
    profit: 'الربح',
    select: 'تحديد',
    approved: 'موافق عليه',
    recommended: 'موصى به',
    contact_us: 'اتصل بنا',
    confirm_order: 'تأكيد الطلب',
    back: 'عودة',
    cancel: 'إلغاء',
    order_confirmation: 'تأكيد الطلب',
    please_review: 'يرجى مراجعة اختيارك أدناه',
    selected: 'محدد',
    total_profit: 'إجمالي الربح',
    claim_now: 'اطلب الآن',
    modal_price: 'سعر رأس المال',
    total_withdraw: 'إجمالي السحب',
    limited_offer: 'توفر محدود • حصري في عطلة نهاية الأسبوع',
    design_special: 'تصميم خاص متميز',
    weekend_collection: 'مجموعة عطلة نهاية الأسبوع',
    payment_title: 'تفاصيل الدفع',
    payment_note: 'ملاحظة: بمجرد الدفع، يرجى تأكيد إثبات الدفع لخدمة العملاء',
    confirm_wa: 'تأكيد واتساب',
    bank: 'بنك',
    account_name: 'اسم الحساب',
    account_no: 'رقم الحساب',
    nominal: 'المبلغ',
    // Login Page
    full_name: 'الاسم الكامل',
    phone_number: 'رقم الهاتف',
    password: 'كلمة المرور',
    login: 'تسجيل الدخول',
    processing: 'جارٍ المعالجة...',
    enter_world: 'أدخل عالم غوتشي',
    copyright: '© 2025 Guccio Gucci S.p.A.',
    fill_fields: 'يرجى ملء جميع الحقول',
  },
  fr: {
    agenda: 'AGENDA',
    price: 'Prix',
    benefit: 'Avantage',
    profit: 'Profit',
    select: 'SÉLECTIONNER',
    approved: 'APPROUVÉ',
    recommended: 'RECOMMANDÉ',
    contact_us: 'CONTACTEZ-NOUS',
    confirm_order: 'CONFIRMER LA COMMANDE',
    back: 'RETOUR',
    cancel: 'ANNULER',
    order_confirmation: 'CONFIRMATION DE COMMANDE',
    please_review: 'Veuillez vérifier votre sélection ci-dessous',
    selected: 'SÉLECTIONNÉ',
    total_profit: 'PROFIT TOTAL',
    claim_now: 'RÉCLAMER MAINTENANT',
    modal_price: 'PRIX DU CAPITAL',
    total_withdraw: 'RETRAIT TOTAL',
    limited_offer: 'Disponibilité Limitée • Exclusivité Week-end',
    design_special: 'DESIGN SPÉCIAL PREMIUM',
    weekend_collection: 'COLLECTION WEEK-END',
    payment_title: 'Détails du Paiement',
    payment_note: 'Note : Une fois le paiement effectué, veuillez confirmer la preuve de paiement au Service Client',
    confirm_wa: 'CONFIRMER WHATSAPP',
    bank: 'Banque',
    account_name: 'Nom du Compte',
    account_no: 'N° de Compte',
    nominal: 'Montant',
    // Login Page
    full_name: 'Nom Complet',
    phone_number: 'Numéro de Téléphone',
    password: 'Mot de Passe',
    login: 'Connexion',
    processing: 'Traitement...',
    enter_world: 'ENTREZ DANS LE MONDE DE GUCCI',
    copyright: '© 2025 Guccio Gucci S.p.A.',
    fill_fields: 'Veuillez remplir tous les champs',
  },
  de: {
    agenda: 'AGENDA',
    price: 'Preis',
    benefit: 'Vorteil',
    profit: 'Gewinn',
    select: 'AUSWÄHLEN',
    approved: 'GENEHMIGT',
    recommended: 'EMPFOHLEN',
    contact_us: 'KONTAKTIEREN SIE UNS',
    confirm_order: 'BESTELLUNG BESTÄTIGEN',
    back: 'ZURÜCK',
    cancel: 'ABBRECHEN',
    order_confirmation: 'BESTELLBESTÄTIGUNG',
    please_review: 'Bitte überprüfen Sie Ihre Auswahl unten',
    selected: 'AUSGEWÄHLT',
    total_profit: 'GESAMTGEWINN',
    claim_now: 'JETZT BEANSPRUCHEN',
    modal_price: 'KAPITALPREIS',
    total_withdraw: 'GESAMTAUSZAHLUNG',
    limited_offer: 'Begrenzte Verfügbarkeit • Wochenende Exklusiv',
    design_special: 'PREMIUM SPEZIALDESIGN',
    weekend_collection: 'WOCHENEND-KOLLEKTION',
    payment_title: 'Zahlungsdetails',
    payment_note: 'Hinweis: Nach erfolgter Zahlung bestätigen Sie bitte den Zahlungsnachweis beim Kundenservice',
    confirm_wa: 'WHATSAPP BESTÄTIGEN',
    bank: 'Bank',
    account_name: 'Kontoname',
    account_no: 'Kontonummer',
    nominal: 'Betrag',
    // Login Page
    full_name: 'Vollständiger Name',
    phone_number: 'Telefonnummer',
    password: 'Passwort',
    login: 'Anmelden',
    processing: 'Verarbeitung...',
    enter_world: 'BETRETEN SIE DIE WELT VON GUCCI',
    copyright: '© 2025 Guccio Gucci S.p.A.',
    fill_fields: 'Bitte füllen Sie alle Felder aus',
  },
  ja: {
    agenda: 'アジェンダ',
    price: '価格',
    benefit: '利益',
    profit: '利益',
    select: '選択',
    approved: '承認済み',
    recommended: '推奨',
    contact_us: 'お問い合わせ',
    confirm_order: '注文を確定',
    back: '戻る',
    cancel: 'キャンセル',
    order_confirmation: '注文確認',
    please_review: '以下の選択内容をご確認ください',
    selected: '選択済み',
    total_profit: '総利益',
    claim_now: '今すぐ請求',
    modal_price: '資本価格',
    total_withdraw: '総引き出し',
    limited_offer: '在庫僅少 • 週末限定',
    design_special: 'プレミアム特別デザイン',
    weekend_collection: '週末コレクション',
    payment_title: '支払い詳細',
    payment_note: '注：支払いが完了したら、カスタマーサービスに支払い証明を確認してください',
    confirm_wa: 'WHATSAPP 確認',
    bank: '銀行',
    account_name: '口座名義',
    account_no: '口座番号',
    nominal: '金額',
    // Login Page
    full_name: '氏名',
    phone_number: '電話番号',
    password: 'パスワード',
    login: 'ログイン',
    processing: '処理中...',
    enter_world: 'GUCCIの世界へ',
    copyright: '© 2025 Guccio Gucci S.p.A.',
    fill_fields: 'すべての項目に入力してください',
  },
  ko: {
    agenda: '의제',
    price: '가격',
    benefit: '혜택',
    profit: '이익',
    select: '선택',
    approved: '승인됨',
    recommended: '추천',
    contact_us: '문의하기',
    confirm_order: '주문 확인',
    back: '뒤로',
    cancel: '취소',
    order_confirmation: '주문 확인',
    please_review: '아래 선택 사항을 검토하십시오',
    selected: '선택됨',
    total_profit: '총 이익',
    claim_now: '지금 청구',
    modal_price: '자본 가격',
    total_withdraw: '총 인출',
    limited_offer: '한정 수량 • 주말 독점',
    design_special: '프리미엄 스페셜 디자인',
    weekend_collection: '주말 컬렉션',
    payment_title: '결제 세부 정보',
    payment_note: '참고: 결제가 완료되면 고객 센터에 결제 증명을 확인하십시오',
    confirm_wa: 'WHATSAPP 확인',
    bank: '은행',
    account_name: '예금주',
    account_no: '계좌 번호',
    nominal: '금액',
    // Login Page
    full_name: '성명',
    phone_number: '전화번호',
    password: '비밀번호',
    login: '로그인',
    processing: '처리 중...',
    enter_world: 'GUCCI의 세계로 입장',
    copyright: '© 2025 Guccio Gucci S.p.A.',
    fill_fields: '모든 필드를 채워주세요',
  }
};

// 3. Create Context
interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<LanguageCode>('id');

  const t = (key: string): string => {
    return DICTIONARY[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
